describe('My First Test', ( )=> {
    beforeEach(( )=>{
        cy.viewport(412, 914)
        cy.visit('/home')
    })
    it('Primer testing' , ( )=>{
        cy.contains('Nombre')
        cy.get('input[name="usuario"]').should('be.visible')
        cy.get('input[name="usuario"]').type('Daniel')
        cy.get('input[name="password"]').type('1234')
        cy.contains('Aceptar').click()
        cy.url().should('include','/inicio')
    })
    it('Segundo testing' , ( )=>{
        cy.get('input[name="usuario"]').type('Daniel')
        cy.get('input[name="password"]').type('1234')
        cy.contains('Aceptar').click()
        cy.contains('Buscar')
        cy.contains('Cerrar').click()
        cy.contains('Aceptar').click()
    })
    it('Tercer testing' , ( )=>{
        cy.get('input[name="usuario"]').type('Daniel')
        cy.get('input[name="password"]').type('1234')
        cy.contains('Aceptar').click()
        cy.contains('Buscar').click()
        cy.contains('Volver').click()
    })
    it('Cuarto testing' , ( )=>{
        cy.get('input[name="usuario"]').type('Daniel')
        cy.get('input[name="password"]').type('1234')
        cy.contains('Aceptar').click()
        cy.contains('Iniciar').click()
        cy.contains('Volver').click()
    })
    it('Quinto testing' , ( )=>{
        cy.get('input[name="usuario"]').type('Daniel')
        cy.get('input[name="password"]').type('1234')
        cy.contains('Aceptar').click()
        cy.contains('Iniciar').click()
        cy.contains('Volver').click()
        cy.contains('Buscar').click()
        cy.contains('Volver').click()
        cy.contains('Cerrar').click()
    })
})